### ISSUE TITLE
LearnIDE major bugs with every Javascript lesson 

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-create-objects-lab#14]
```
  0 passing (9ms)
  1 failing
  1) index "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)
npm ERR! Test failed.  See above for more details.
```
My test is showing the error above. 
The test passes without even writing a single line of code and with that error on the screen. 
I get the following noise after removing node_modules and package-lock.json and then running npm install
```
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN mocha-jsdom@1.2.0 requires a peer of jsdom@>10.0.0 but none is installed. You must install peer dependencies yourself.
```
I've tried replicating the bug but I'm limited without root access in the LearnIDE.
This is discouraging as the test pass without a single line of code and I'm spending more time trying to fix the IDE than actual coding, which would be fun if I had root access. Please update all packages, along w/ node.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
